#pragma once

#ifndef MAX_REG_KEY_NAME_SIZE
#define MAX_REG_KEY_NAME_SIZE   255
#endif // !MAX_REG_KEY_NAME_SIZE

#ifndef MAX_REG_VALUE_NAME_SIZE
#define MAX_REG_VALUE_NAME_SIZE 16383
#endif // !MAX_REG_VALUE_NAME_SIZE

#ifndef MAX_REG_VALUE_DATA_SIZE
#define MAX_REG_VALUE_DATA_SIZE 1024000
#endif // !MAX_REG_VALUE_DATA_SIZE

#ifndef REG_VER_MAJOR
#define REG_VER_MAJOR           6
#endif // !REG_VER_MAJOR

#ifndef REG_VER_MINOR
#define REG_VER_MINOR           1
#endif // !REG_VER_MINOR

#ifndef ERROR_OPEN_HIVE_FAILED
#define ERROR_OPEN_HIVE_FAILED  -11
#endif // !ERROR_OPEN_HIVE_FAILED

#ifndef ERROR_CREATE_HIVE_FAILED
#define ERROR_CREATE_HIVE_FAILED  -12
#endif // !ERROR_CREATE_HIVE_FAILEF

#ifndef ERROR_CREATE_KEY_FAILED
#define ERROR_CREATE_KEY_FAILED  -13
#endif // !ERROR_CREATE_KEY_FAILED

#ifndef SUCCEED
#define SUCCEED  0
#endif // !SECCEED

#ifdef ERROR_FILE_NOT_FOUND
#define ERROR_FILE_NOT_FOUND  -1
#endif // !ERROR_FILE_NOT_FOUND

